#ifndef MARIO_PLATFORM_CONFIG_H
#define MARIO_PLATFORM_CONFIG_H

#include "xparameters.h"

/*
 * If Vivado assigns different instance names, change these macros.
 */
#ifndef MARIO_SPRITE_CTRL_BASEADDR
#define MARIO_SPRITE_CTRL_BASEADDR \
    XPAR_SPRITE_ENGINE_AXI_LITE_0_S_AXI_BASEADDR
#endif

#ifndef MARIO_AXI_DMA_DEVICE_ID
#define MARIO_AXI_DMA_DEVICE_ID XPAR_AXI_DMA_0_DEVICE_ID
#endif

#ifndef MARIO_SD_SPI_DEVICE_ID
#define MARIO_SD_SPI_DEVICE_ID XPAR_AXI_QUAD_SPI_0_DEVICE_ID
#endif

#ifndef MARIO_UART_DEVICE_ID
#define MARIO_UART_DEVICE_ID XPAR_AXI_UARTLITE_0_DEVICE_ID
#endif

#ifndef MARIO_AXI_VDMA_DEVICE_ID
#define MARIO_AXI_VDMA_DEVICE_ID XPAR_AXI_VDMA_0_DEVICE_ID
#endif

#define MARIO_GAME_HZ 60U
#define MARIO_FRAME_US 16667U

#define MARIO_FRAME_WIDTH       1280U
#define MARIO_FRAME_HEIGHT      720U
#define MARIO_FRAME_STRIDE      (MARIO_FRAME_WIDTH * 2U)
#define MARIO_FRAME_BYTES       (MARIO_FRAME_STRIDE * MARIO_FRAME_HEIGHT)
#define MARIO_FRAME_STORE_COUNT 3U
#define MARIO_FRAME0_ADDR       0x8C000000U
#define MARIO_FRAME1_ADDR       0x8C200000U
#define MARIO_FRAME2_ADDR       0x8C400000U

#endif
